version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root